/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppFollowingRouteImport } from './routes/_app.following'
import { Route as AppProfileUsernameRouteImport } from './routes/_app.profile.$username'
import { Route as AppPostIdRouteImport } from './routes/_app.post.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowingRoute = AppFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUsernameRoute = AppProfileUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppPostIdRoute = AppPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/following': typeof AppFollowingRoute
  '/home': typeof AppHomeRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/post/$id': typeof AppPostIdRoute
  '/profile/$username': typeof AppProfileUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/following': typeof AppFollowingRoute
  '/home': typeof AppHomeRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/post/$id': typeof AppPostIdRoute
  '/profile/$username': typeof AppProfileUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/following': typeof AppFollowingRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/post/$id': typeof AppPostIdRoute
  '/_app/profile/$username': typeof AppProfileUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/following'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/post/$id'
    | '/profile/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/following'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/post/$id'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/following'
    | '/_app/home'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/post/$id'
    | '/_app/profile/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/following': {
      id: '/_app/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof AppFollowingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/post/$id': {
      id: '/_app/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AppPostIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileUsernameRoute: AppProfileUsernameRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppFollowingRoute: typeof AppFollowingRoute
  AppHomeRoute: typeof AppHomeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppPostIdRoute: typeof AppPostIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFollowingRoute: AppFollowingRoute,
  AppHomeRoute: AppHomeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppPostIdRoute: AppPostIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
